let i = 0;
const templateConfig = [
	{
		id: i,
		name: "prod1",
		imageSrc: "product.png",
		type: "Sweeps",
		props: [
			{ type: "text", name: "brand", value: "Harbor Freight" },
			{ type: "color", name: "mainColor", value: "rgb(229, 32, 55)" },
			{ type: "color", name: "secondaryColor", value: "rgb(255, 255, 255)" },
			{ type: "color", name: "title_color_text", value: "#000000" },
			{ type: "color", name: "description_color_text", value: "rgb(229, 32, 55)" },
			{ type: "color", name: "text_color", value: "#ffffff" },
			{ type: "color", name: "text_button_color", value: "#ffffff" },
			{ type: "color", name: "button_color", value: "#ffffff" },
			{ type: "image", name: "titleImg", value: "https://devsrv.neptuneads.com/us-harbp/files/logo2.png", size: "100%" },
			{ type: "image", name: "productImg", value: "https://devsrv.neptuneads.com/us-harbp/files/product.png", size: "100%" },
			{ type: "text", name: "height_creative", value: "950px" },
			{ type: "text", name: "product", value: "Pittsburgh 225 Piece Tool Set" },
			{ type: "text", name: "creativeTitle", value: "It will take you only a minute to receive this fantastic prize!" },
			{ type: "text", name: "surveyTitle", value: "TAKE SURVEY AND WIN REWARD!" },
			{ type: "text", name: "title", value: "Congratulations!" },
			{ type: "text", name: "paragraph", value: "Share your valuable insights and win big! You've been chosen for a quick survey about store promotions at " },
			{ type: "text", name: "paragraph2", value: "By participating, you could win " },
			{ type: "text", name: "claimText", value: "To claim, simply take this short survey about your experience with " },
			{ type: "text", name: "buttonText", value: "GET STARTED NOW" },
			{ type: "text", name: "unsubscribeText", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here" },
			{ type: "color", name: "color_text_warning_1", value: "#666" },
			// { type: "size", name: "titleImg", value: "100%" },
			// { type: "size", name: "productImg", value: "100%" },
		],
		// template: ProductTemplate,
	},
	{
		id: i=i+1,
		name: "prod2",
		imageSrc: "prod2.png",
		type: "Sweeps",
		props: [
			{ type: "text", name: "brand", value: "STARBUCKS " },
			{ type: "color", name: "mainColor", value: "rgb(28, 30, 117)" },
			{ type: "color", name: "secondaryColor", value: "rgb(155, 242, 209)" },
			{ type: "image", name: "logoImg", value: "https://686.efuserassets.com/686/offers/14121/c/40989/assets/logo1.png", size: "100%" },
			{ type: "image", name: "productImg", value: "https://686.efuserassets.com/686/offers/14121/c/40989/assets/product.png", size: "100%" },
			{ type: "text", name: "product", value: " COFFEE LOVERS BOX" },
			{ type: "text", name: "buttonText", value: "Secure Your Chance to Win!" },
			{ type: "text", name: "text01", value: "" },
			{ type: "text", name: "text02", value: "Time is Running Out" },
			{ type: "text", name: "text03", value: "Last chance to win a brand new " },
			{ type: "text", name: "text04", value: "GET YOURS" },
			{ type: "text", name: "text05", value: "Simply answer a few questions and Win" },
			{ type: "text", name: "text06", value: "Your chance to shine awaits!" },
			{ type: "text", name: "unsubscribeText", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here." },
		],
		// template: ProductTemplate2,
	},
	{
		id: i=i+1,
		name: "prod3",
		imageSrc: "prod3.png",
		type: "Sweeps",
		props: [
			{ type: "text", name: "brand", value: "Walmart" },
			{ type: "color", name: "mainColor", value: "rgb(0, 115, 219)" },
			{ type: "color", name: "secondaryColor", value: "rgb(255, 194, 34)" },
			{ type: "color", name: "buttonColor", value: "rgb(255, 194, 34)" },
			{ type: "color", name: "buttonTextColor", value: "rgb(255, 255, 255)" },
			{ type: "color", name: "buttonText2Color", value: "rgb(255, 255, 255)" },
			{ type: "image", name: "logoImg", value: "https://devsrv.neptuneads.com/us-walfrost/images/logo.png", size: "100%" },
			{ type: "image", name: "productImg", value: "https://devsrv.neptuneads.com/us-walfrost/images/product.png", size: "100%" },
			{ type: "text", name: "product", value: "Ninja FrostVault Hard Cooler" },
			{ type: "text", name: "buttonText", value: "START SURVEY" },
			{ type: "text", name: "buttonText2", value: "GET STARTED! IT'S FREE" },
			{ type: "text", name: "text01", value: "Marketing Survey" },
			{ type: "text", name: "text02", value: "Answer & Win!" },
			{ type: "text", name: "text03", value: "You have been chosen to participate in our Loyalty Program for FREE! It will take you only a minute to receive this fantastic prize." },
			{ type: "text", name: "text04", value: " Inventory Low" },
			{ type: "text", name: "text05", value: "It's worth hurrying! Due to high demand, there are only a few pieces left available." },
			{ type: "text", name: "unsubscribeText", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here." },
			{ type: "color", name: "colorText1", value: "rgb(255, 255, 255)" },
			{ type: "color", name: "colorText2", value: "rgb(0, 0, 0)" },
		],
		// template: ProductTemplate2,
	},{
		id: i=i+1,
		name: "prod4",
		imageSrc: "prod4.png",
		type: "Sweeps",
		props: [
			{ type: "image", name: "logo", value: "https://686.efuserassets.com/686/offers/13830/c/39621/assets/logo.png", size: "100%"},
			{ type: "image", name: "product_img", value: "https://686.efuserassets.com/686/offers/13830/c/39621/assets/product.png", size: "100%"},
			{ type: "text", name: "text_1", value: "YOU ARE OUR WINNER!" },
			{ type: "text", name: "product_title", value: "Walmart $500 Gift Card" },
			{ type: "text", name: "text_2", value: "A delivery fee may apply" },
			{ type: "color", name: "color_text2", value: "#235ba9" },
			{ type: "text", name: "text_3", value: "Customer number:" },
			{ type: "text", name: "text_4", value: "#4864370221" },
			{ type: "text", name: "button_text", value: "Click Here To Claim"},
			{ type: "color", name: "color_button", value: "#d4141f" },
			{ type: "color", name: "color_text_button", value: "#FFFFFF" },
			{ type: "text", name: "border_radius", value: "999px" },
			{ type: "color", name: "bg_color", value: "#FFFFFF" },
			{ type: "color", name: "color_text", value: "#000" },
			{ type: "text", name: "code", value: "#4864370221" },
		],
		// template: ProductTemplate,
	},
	{
		id: i=i+1,
		name: "prod5",
		imageSrc: "prod5.png",
		type: "Sweeps",
		props: [
			{ type: "image", name: "background_image", value: "https://686.efuserassets.com/686/offers/14221/c/41396/assets/bg5.png", size: "100%"},
			{ type: "color", name: "background_color", value: "#fff"},
			{ type: "image", name: "logo", value: "https://686.efuserassets.com/686/offers/14221/c/41395/assets/logo.png",size: "100%"},
			{ type: "color", name: "second_background_color", value: "#fff" },
			{ type: "text", name: "product_title", value: "BISSELL CrossWave Vacuum Cleaner" },
			{ type: "image", name: "product_image", value: "https://686.efuserassets.com/686/offers/14221/c/41395/assets/product.png",size: "100%" },
			{ type: "image", name: "icon1", value: "https://686.efuserassets.com/686/offers/14221/c/41396/assets/icon.png",size: "100%" },
			{ type: "image", name: "icon2", value: "https://686.efuserassets.com/686/offers/14221/c/41396/assets/time-icon.png",size: "100%"},
			{ type: "color", name: "color_text_free", value: "rgb(226, 0, 26)"},
			{ type: "color", name: "button_color_1", value: "#005daa" },
			{ type: "color", name: "button_color_text_1", value: "#FFFFFF" },
			{ type: "color", name: "button_color_2", value: "rgb(226, 0, 26)" },
			{ type: "color", name: "button_color_text_2", value: "#FFFFFF" },
			{ type: "color", name: "color_text_2", value: "rgb(226, 0, 26)" },
			{ type: "color", name: "color_warning", value: "#797979" },
		],
		// template: ProductTemplate,
	},
	{
		id: i=i+1,
		name: "track1",
		imageSrc: "trackntrace.png",
		type: "Track & Trace",
		props: [
			{ type: "text", name: "brand", value: "PackageDelivery" },
			{ type: "color", name: "mainColor", value: "#2D1D57" },
			{ type: "color", name: "secondaryColor", value: "#FA6908" },
			{ type: "image", name: "logoImg", value: "https://686.efuserassets.com/686/offers/14122/c/40996/assets/logo.png", size: "100%" },
			{ type: "image", name: "productImg", value: "https://686.efuserassets.com/686/offers/14122/c/40996/assets/p2.png", size: "100%" },
			{ type: "text", name: "text01", value: "Claim your UNCLAIMED PACKAGE" },
			{ type: "text", name: "text02", value: "Your Winning Prize" },
			{ type: "text", name: "text03", value: "Please confirm and provide your shipping information!" },
			{ type: "text", name: "buttonText", value: "CLAIM YOUR LUGGAGE" },
			{ type: "text", name: "unsubscribeText", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here." },
		],
		// template: TrackTemplate,
	},
	{
		id: i=i+1,
		name: "track2",
		imageSrc: "trackntrace2.png",
		type: "Track & Trace",
		props: [
			{ type: "text", name: "brand", value: "PackageDelivery" },
			{ type: "color", name: "background_color", value: "#f5f5f5" },
			{ name: "mainColor", type: "color", value: "rgb(45,29,87,1) " },
			{ name: "secundaryColor", type: "color", value: "rgb(250,105,8,1)" },
			{ name: "title_img", type: "image", value: "https://686.efuserassets.com/686/offers/14122/c/40996/assets/logo.png", size: "100%" },
			{ name: "intro", type: "text", value: "Answer & win!" },
			{ name: "intro_background_color", type: "color", value: "red" },
			{ name: "color_text_intro", type: "color", value: "#ffffff" },
			{ name: "text_1", type: "text", value: "A mystery prize from" },
			{ name: "color_text_1", type: "color", value: "#ffffff" },
			{ name: "text_2", type: "text", value: "Unclaimed Package" },
			{ name: "color_text_2", type: "color", value: "#ffffff" },
			{ name: "product_img", type: "image", value: "https://686.efuserassets.com/686/offers/14122/c/40996/assets/p2.png", size: "100%" },
			{ name: "secondary_background_color", type: "color", value: "#ffffff" },
			{ name: "text_3", type: "text", value: "Dear FedEx Customer," },
			{ name: "color_text", type: "color", value: "#000000" },
			{ name: "text_4", type: "text", value: "We would like to offer you a unique opportunity to receive a brand new Unclaimed Package!" },
			{ name: "text_5", type: "text", value: " To claim, simply take this short survey about your experience with us." },
			{ name: "text_6", type: "text", value: "GET STARTED NOW!" },
			{ name: "color_text_button", type: "text", value: "grey" },
			{ name: "color_button", type: "text", value: "red" },
			{ name: "unsuscribe_text", type: "text", value: "If you no longer wish to receive these emails, you may unsubscribe by" },
			{ name: "click_text", type: "text", value: "clicking here." },
		],
	},
	{
		id: i=i+1,
		name: "track3",
		imageSrc: "trackntrace3.png",
		type: "Track & Trace",
		props: [
			{ type: "text", name: "brand", value: "PackageDelivery" },
			{ type: "color", name: "mainColor", value: "rgb(72, 0, 255)" },
			{ type: "color", name: "buttonColor", value: "rgb(255, 100, 0)" },
			{ name: "textColor", type: "color", value: "rgb(0, 0, 0, 1)" },
			{ name: "logoImg", type: "image", value: "https://686.efuserassets.com/686/offers/14122/c/40996/assets/logo.png", size: "100%" },
			{ name: "productImg", type: "image", value: "https://686.efuserassets.com/686/offers/14122/c/40996/assets/p2.png", size: "100%" },
			{ name: "text_1", type: "text", value: "Get Your Unclaimed Package!" },
			{ name: "text_2", type: "text", value: "Dear Customer, " },
			{ name: "text_3", type: "text", value: "You have (1) package waiting for delivery." },
			{ name: "text_4", type: "text", value: "Confirm your shipping details" },
			{ name: "text_5", type: "text", value: "115 E 23rd St New York, NY, US 10010" },
			{ name: "textButton", type: "text", value: "CONTINUE" },
			{ name: "textButton2", type: "text", value: "SCHEDULE YOUR DELIVERY" },
			{ name: "colorTextButton", type: "color", value: "rgb(255, 255, 255)" },
			{ name: "colorTextButton2", type: "color", value: "rgb(255, 255, 255)" },
			{ name: "unsubscribe_text", type: "text", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here." },
		],
	},
	{
		id: i=i+1,
		name: "offerwall",
		imageSrc: "offerwall.png",
		type: "Offer Wall",
		props: [
			{ type: "color", name: "mainColor", value: "#000 " },
			{ type: "color", name: "secondaryColor", value: "#333" },
			{ type: "image", name: "title_img", value: "https://1687.efuserassets.com/1687/offers/457/c/1598/assets/tmobile-color.png", size: "100%" },
			{ type: "image", name: "product_img", value: "https://1687.efuserassets.com/1687/offers/7/c/2627/assets/feature.png", size: "100%" },
			{ type: "color", name: "color_buttom", value: "#007ec7" },
			{ type: "text", name: "intro", value: "ANSWER & WIN!" },
			{ type: "text", name: "text_1", value: "Exclusive" },
			{ type: "text", name: "text_2", value: "$100 REWARDS" },
			{ type: "text", name: "text_3", value: "You have been chosen to participate in our Loyalty Program for FREE! It will take you only a minute to receive this fantastic prize." },
			{ type: "text", name: "text_buttom", value: "GET STARTED NOW!" },
			{ type: "text", name: "text_warning_1", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here" },
			{ type: "color", name: "intro_color", value: "#007ec7" },
			{ type: "color", name: "color_text_warning_1", value: "#4a4954" },
		],
		// template: OfferWallTemplate,
	},
	{
		id: i=i+1,
		name: "offerwall2",
		imageSrc: "offerwall2.png",
		type: "Offer Wall",
		props: [
			{ type: "color", name: "mainColor", value: "#007ec7" },
			{ type: "color", name: "secondaryColor", value: "#ffffff" },
			{ type: "image", name: "title_img", value: "https://logos-world.net/wp-content/uploads/2021/10/Sams-Club-Logo.png", size: "25%" },
			{ type: "image", name: "product_img", value: "https://devsrv.neptuneads.com/uk-apbox/Daco_4935704.png", size: "35%" },
			{ type: "color", name: "color_buttom", value: "#1e2020" },
			{ type: "text", name: "intro", value: "YOUR OPINION IS IMPORTANT" },
			{ type: "text", name: "text_1", value: "Exclusive" },
			{ type: "text", name: "text_2", value: "YOU CAN GET A $100 REWARD" },
			{ type: "text", name: "text_3", value: "Take a short survey to claim your $100 reward" },
			{ type: "text", name: "text_4", value: "Click the button below to get started" },
			{ type: "text", name: "text_buttom", value: "GET STARTED NOW!" },
			{ type: "text", name: "text_warning_1", value: "115 E 23rd St New York, NY US 10010" },
			{ type: "text", name: "text_warning_2", value: "Unsubscribe here" },
			{ type: "color", name: "intro_color", value: "#ffffff" },
		],
		// template: OfferWallTemplate,
	},
	{
		id: i=i+1,
		name: "strg",
		imageSrc: "storage.png",
		type: "Storage Limit",
		props: [
			{ type: "text", name: "brand", value: "iCloud " },

			{ type: "color", name: "mainColor", value: "#fff" },
			{ type: "color", name: "backgroundColor", value: "#efefef" },
			{ type: "color", name: "buttonColor", value: "#0071E3" },
			{ type: "color", name: "textButtonColor", value: "#ffffff" },
			{ type: "color", name: "colorText", value: "#000" },

			{ type: "image", name: "logoImg", value: "https://devsrv.neptuneads.com/be-iphn/files/favicon.ico", size: "100%" },
			{ type: "image", name: "productImg", value: "https://686.efuserassets.com/686/offers/13105/c/39526/assets/feature.png", size: "100%" },

			{ type: "text", name: "title", value: "You have reached your storage limit" },
			{ type: "text", name: "text01", value: "Dear customer, Your storage is full." },
			{ type: "text", name: "text03", value: "But as part of our loyalty program, you can now receive an additional 50 GB for free before the files on your account are deleted." },
			{ type: "text", name: "buttonText", value: "Get 50 GB" },
			{ type: "text", name: "text05", value: "* After signing up, you need to enter your credit card information to validate your ID. We will not charge any amount." },
			{ type: "text", name: "unsubscribeText", value: "If you no longer wish to receive these emails, you can unsubscribe at unsubscribe here." },
		],
		// template: StorageLimitTemplate,
	},
	{
		id: i=i+1,
		name: "subs1",
		imageSrc: "subscription.png",
		type: "Subscription",
		props: [
			{ type: "text", name: "brand", value: "Paramount" },
			{ type: "color", name: "mainColor", value: "#fff" },
			{ type: "color", name: "colorButton", value: "#e50914" },
			{ type: "image", name: "titleImg", value: "https://686.efuserassets.com/686/offers/13672/c/38753/assets/logo2.png", size: "100%" },
			{ type: "image", name: "productImg", value: "https://686.efuserassets.com/686/offers/13672/c/38753/assets/product2.png", size: "100%" },
			{ type: "text", name: "title", value: "Your membership has expired" },
			{ type: "text", name: "text01", value: "Dear Customer, Your membership has expired!" },
			{ type: "text", name: "text02", value: "You can now extend it for FREE for 90 days as part of our loyalty program" },
			{ type: "text", name: "buttonText", value: "Extend for Free" },
			{ type: "text", name: "text03", value: "*After registering, you must enter: your credit card details to confirm your account " },
			{ type: "text", name: "text04", value: "We will not charge any amount" },
			{ type: "text", name: "unsubscribeText", value: "If you no longer wish to receive these emails, you may unsubscribe by clicking here." },
		],
		// template: SubscriptionTemplate,
	},
	{
		id: i=i+1,
		name: "limof",
		imageSrc: "limof.png",
		type: "Limited Offer",
		props: [
			{ type: "brand", name: "brand", value: "Netflix" },
			{ type: "color", name: "mainColor", value: "#000000" },
			{ type: "color", name: "secondaryColor", value: "#efefef" },
			{ type: "color", name: "textColor", value: "#ffffff" },
			{ type: "image", name: "title_img", value: "https://686.efuserassets.com/686/offers/13758/c/39190/assets/l.png", size: "100%" },
			{ type: "image", name: "product_img", value: "https://686.efuserassets.com/686/offers/13758/c/39190/assets/i.png", size: "100%" },
			{ type: "color", name: "color_button", value: "#e50914" },
			{ type: "text", name: "intro", value: "Hurry! This offer will expire soon!" },
			{ type: "text", name: "intro_2", value: "Answer 3 questions and save 95% on yearly subscription!" },
			{ type: "text", name: "text_1", value: "Dear subscriber," },
			{ type: "text", name: "text_3", value: "you've been randomly selected." },
			{ type: "text", name: "text_4", value: "Please answer these 3 questions and enjoy unlimited movies, TV shows and more! Watch anywhere. Cancel at anytime." },
			{ type: "text", name: "text_buttom", value: "Answer Now" },
			{ type: "text", name: "text_warning_1", value: "* After signing up, you have to insert your credit card details for validation of your account." },
			{ type: "text", name: "text_warning_2", value: "We will not withdraw any amount." },
		],
		// template: LimitedOfferTemplate,
	},
];

export default templateConfig;
